---
abstract: 'Downloading material (video, text, pdf ...) from Coursera.org online classes.'
author:
  - 'Ovidiu Nita Tatar <ovn.tatar@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Coursera
provides:
  WWW::Coursera:
    file: lib/WWW/Coursera.pm
    version: 0.03
requires:
  Carp: 1.26
  HTTP::Cookies: 6.01
  WWW::Mechanize: 1.72
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
